export const INC_CORRECT = 'INC_CORRECT';
export const INC_WRONG = 'INC_WRONG';
export const RESET = 'RESET';

export const INC_CORRECT_INT = 'INC_CORRECT_INT';
export const INC_WRONG_INT = 'INC_WRONG_INT';

export const INC_CORRECT_NOTE = 'INC_CORRECT_NOTE';
export const INC_WRONG_NOTE = 'INC_WRONG_NOTE';

export const INC_CORRECT_CHORD = 'INC_CORRECT_CHORD';
export const INC_WRONG_CHORD = 'INC_WRONG_CHORD';

export const SET_PRAC_MODE_NOTE = 'SET_PRAC_MODE_NOTE';
export const SET_PRAC_MODE_INT = 'SET_PRAC_MODE_INT';
export const SET_STATS = 'SET_STATS';
export const SET_STATSID = 'SET_STATSID';

export const IGNORE_GOAL = 'IGNORE_GOAL';
export const SHOW_GOAL_PANEL = 'SHOW_GOAL_PANEL';
export const CHANGE_INT_GOAL = 'CHANGE_INT_GOAL';
export const CHANGE_NOTE_GOAL = 'CHANGE_NOTE_GOAL';
export const CHANGE_CHORD_GOAL = 'CHANGE_CHORD_GOAL';
export const CHANGE_INT_GOAL_REACHED = 'CHANGE_INT_GOAL_REACHED';
export const CHANGE_NOTE_GOAL_REACHED = 'CHANGE_NOTE_GOAL_REACHED';
export const CHANGE_CHORD_GOAL_REACHED = 'CHANGE_CHORD_GOAL_REACHED';

export const SHOW_AUTH_PANEL = 'SHOW_AUTH_PANEL';
export const SET_AUTH_MODE = 'SET_AUTH_MODE';
export const SET_IS_AUTH = 'SET_IS_AUTH';
export const LOGOUT = 'LOGOUT';
export const SET_USERID = 'SET_USERID';
export const SET_TOKEN = 'SET_TOKEN';
